spring:
  datasource:
    url: jdbc:h2:mem:foodvoice
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    group: true

jwt:
  token:
    secret: 'FoodVoiceRESTfulAPI'
    expired: 3600000

food-voice:
  voice:
    change-stop-time: '11:00'